export const games = [
    {
        id: 'dark-souls',
        imgSrc: 'https://tinyurl.com/4dwmse5a',
        longTitle: 'Dark Souls',
        shortName: 'DS',
        title: 'Dark Souls',
        genre: ['Action', 'Role-playing'],
    },
    {
        id: 'kotor',
        imgSrc: 'https://tinyurl.com/bpastw7z',
        longTitle: 'Star Wars: Knights of the Old Republic',
        shortName: 'KOTOR',
        title: 'KOTOR',
        genre: ['Sci-fi', 'Role-playing'],
    },
    {
        id: 'metal-gear-solid',
        imgSrc: 'https://tinyurl.com/4cwkacs7',
        longTitle: 'Metal Gear Solid',
        shortName: 'MGS',
        title: 'Metal Gear Solid',
        genre: ['Action-adventure', 'Stealth'],
    },
    {
        id: 'ff14',
        imgSrc: 'https://tinyurl.com/4dyafufu',
        longTitle: 'Final Fantasy 14',
        shortName: 'FFXIV',
        title: 'FFXIV',
        genre: ['MMORPG', 'Fantasy'],
    },
    {
        id: 'mass-effect',
        imgSrc: 'https://tinyurl.com/2p8nedb6',
        longTitle: 'Mass Effect',
        shortName: 'ME',
        title: 'Mass Effect',
        genre: ['Action', 'Role-playing', 'Sci-fi'],
    },
    {
        id: 'dota-2',
        imgSrc: 'https://tinyurl.com/3ckr2v84',
        longTitle: 'Dota 2',
        shortName: 'Dota 2',
        title: 'Dota 2',
        genre: 'MOBA',
    },
    {
        id: 'jet-set-radio',
        imgSrc: 'https://tinyurl.com/yc7tzc47',
        longTitle: 'Jet Set Radio',
        shortName: 'JSR',
        title: 'Jet Set Radio',
        genre: ['Platform', 'Action', 'Sports'],
    },
    {
        id: 'civ-5',
        imgSrc: 'https://tinyurl.com/25p4s8h3',
        longTitle: 'Sid Meier\'s\ Civilization V',
        shortName: 'Civ 5',
        title: 'Civ 5',
        genre: ['Turn-base Strategy', '4X'],
    },
    {
        id: 'fallout-new-vegas',
        imgSrc: 'https://tinyurl.com/mr2w4ztd',
        longTitle: 'Fallout: New Vegas',
        shortName: 'FNV',
        title: 'Fallout: New Vegas',
        genre: ['Action', 'Role-playing'],
    },
    {
        id: 'disco-elysium',
        imgSrc: 'https://tinyurl.com/4w55j9zz',
        longTitle: 'Disco Elysium',
        shortName: 'Disco Elysium',
        title: 'Disco Elysium',
        genre: 'Role-playing',
    },
];